import type { ArchetypeKey } from './types';

export interface StapleEntry {
  name: string;
  powerScore: number;
  archetypes: ArchetypeKey[];
  cubeTypes: string[];
}

export const KNOWN_CUBE_STAPLES: StapleEntry[] = [
  // ===== White =====
  { name: 'Esper Sentinel', powerScore: 0.85, archetypes: ['WU', 'GW', 'WB'], cubeTypes: [] },
  { name: 'Mother of Runes', powerScore: 0.82, archetypes: ['GW', 'WB', 'RW'], cubeTypes: [] },
  { name: 'Stoneforge Mystic', powerScore: 0.88, archetypes: ['RW', 'WU'], cubeTypes: [] },
  { name: 'Thalia, Guardian of Thraben', powerScore: 0.78, archetypes: ['RW', 'WB', 'GW'], cubeTypes: [] },
  { name: 'Luminarch Aspirant', powerScore: 0.72, archetypes: ['GW', 'WB', 'RW'], cubeTypes: [] },
  { name: 'Adanto Vanguard', powerScore: 0.55, archetypes: ['RW', 'WB'], cubeTypes: [] },
  { name: 'Blade Splicer', powerScore: 0.62, archetypes: ['GW', 'WU'], cubeTypes: [] },
  { name: 'Flickerwisp', powerScore: 0.68, archetypes: ['WU', 'GW'], cubeTypes: [] },
  { name: 'Restoration Angel', powerScore: 0.72, archetypes: ['WU', 'GW'], cubeTypes: [] },
  { name: 'Skyclave Apparition', powerScore: 0.78, archetypes: ['WU', 'GW', 'WB'], cubeTypes: [] },
  { name: 'Swords to Plowshares', powerScore: 0.90, archetypes: [], cubeTypes: [] },
  { name: 'Path to Exile', powerScore: 0.85, archetypes: [], cubeTypes: [] },
  { name: 'Wrath of God', powerScore: 0.82, archetypes: [], cubeTypes: [] },
  { name: 'Day of Judgment', powerScore: 0.68, archetypes: [], cubeTypes: [] },
  { name: 'Council\'s Judgment', powerScore: 0.75, archetypes: [], cubeTypes: [] },
  { name: 'Elspeth, Sun\'s Champion', powerScore: 0.80, archetypes: ['GW', 'WB'], cubeTypes: [] },
  { name: 'Gideon, Ally of Zendikar', powerScore: 0.78, archetypes: ['RW', 'GW', 'WB'], cubeTypes: [] },
  { name: 'Soulherder', powerScore: 0.65, archetypes: ['WU'], cubeTypes: [] },
  { name: 'Ephemerate', powerScore: 0.70, archetypes: ['WU'], cubeTypes: [] },
  { name: 'Porcelain Legionnaire', powerScore: 0.62, archetypes: ['RW', 'GW'], cubeTypes: [] },
  { name: 'Adeline, Resplendent Cathar', powerScore: 0.78, archetypes: ['RW', 'GW'], cubeTypes: [] },
  { name: 'Brimaz, King of Oreskos', powerScore: 0.70, archetypes: ['RW', 'GW'], cubeTypes: [] },

  // ===== Blue =====
  { name: 'Ancestral Recall', powerScore: 0.99, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Time Walk', powerScore: 0.99, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Timetwister', powerScore: 0.88, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Brainstorm', powerScore: 0.82, archetypes: ['UR', 'WU', 'UB'], cubeTypes: [] },
  { name: 'Ponder', powerScore: 0.78, archetypes: ['UR', 'UB', 'UG'], cubeTypes: [] },
  { name: 'Preordain', powerScore: 0.75, archetypes: ['UR', 'UB', 'UG'], cubeTypes: [] },
  { name: 'Force of Will', powerScore: 0.92, archetypes: [], cubeTypes: [] },
  { name: 'Counterspell', powerScore: 0.80, archetypes: ['WU', 'UB', 'UR'], cubeTypes: [] },
  { name: 'Mana Drain', powerScore: 0.90, archetypes: ['UG', 'UR'], cubeTypes: [] },
  { name: 'Jace, the Mind Sculptor', powerScore: 0.92, archetypes: ['WU', 'UB', 'UR'], cubeTypes: [] },
  { name: 'Snapcaster Mage', powerScore: 0.85, archetypes: ['UR', 'UB', 'WU'], cubeTypes: [] },
  { name: 'Vendilion Clique', powerScore: 0.75, archetypes: ['UR', 'UB'], cubeTypes: [] },
  { name: 'True-Name Nemesis', powerScore: 0.82, archetypes: ['UB'], cubeTypes: [] },
  { name: 'Phantasmal Image', powerScore: 0.68, archetypes: ['UB', 'WU'], cubeTypes: [] },
  { name: 'Mulldrifter', powerScore: 0.72, archetypes: ['WU', 'UG'], cubeTypes: [] },
  { name: 'Spellseeker', powerScore: 0.62, archetypes: ['UR', 'UB', 'WU'], cubeTypes: [] },
  { name: 'Upheaval', powerScore: 0.85, archetypes: ['UG'], cubeTypes: [] },
  { name: 'Time Spiral', powerScore: 0.78, archetypes: ['UR', 'UG'], cubeTypes: [] },
  { name: 'Mystic Confluence', powerScore: 0.70, archetypes: ['WU', 'UR'], cubeTypes: [] },
  { name: 'Urza, Lord High Artificer', powerScore: 0.88, archetypes: ['WU'], cubeTypes: [] },
  { name: 'Ledger Shredder', powerScore: 0.68, archetypes: ['UR', 'UB'], cubeTypes: [] },
  { name: 'Occult Epiphany', powerScore: 0.55, archetypes: ['UB', 'UR'], cubeTypes: [] },

  // ===== Black =====
  { name: 'Thoughtseize', powerScore: 0.85, archetypes: ['UB', 'WB', 'BG', 'BR'], cubeTypes: [] },
  { name: 'Inquisition of Kozilek', powerScore: 0.78, archetypes: ['UB', 'WB', 'BG', 'BR'], cubeTypes: [] },
  { name: 'Dark Confidant', powerScore: 0.82, archetypes: ['WB', 'UB', 'BR'], cubeTypes: [] },
  { name: 'Reanimate', powerScore: 0.88, archetypes: ['UB', 'BG'], cubeTypes: [] },
  { name: 'Animate Dead', powerScore: 0.78, archetypes: ['UB', 'BG'], cubeTypes: [] },
  { name: 'Entomb', powerScore: 0.82, archetypes: ['UB', 'BG'], cubeTypes: [] },
  { name: 'Demonic Tutor', powerScore: 0.92, archetypes: [], cubeTypes: [] },
  { name: 'Vampiric Tutor', powerScore: 0.90, archetypes: [], cubeTypes: [] },
  { name: 'Toxic Deluge', powerScore: 0.85, archetypes: [], cubeTypes: [] },
  { name: 'Damnation', powerScore: 0.80, archetypes: [], cubeTypes: [] },
  { name: 'Liliana of the Veil', powerScore: 0.88, archetypes: ['UB', 'BR', 'BG'], cubeTypes: [] },
  { name: 'Grave Titan', powerScore: 0.82, archetypes: ['UB', 'BG'], cubeTypes: [] },
  { name: 'Grief', powerScore: 0.78, archetypes: ['UB', 'WB'], cubeTypes: [] },
  { name: 'Murderous Rider', powerScore: 0.62, archetypes: ['WB', 'UB'], cubeTypes: [] },
  { name: 'Braids, Cabal Minion', powerScore: 0.68, archetypes: ['BR', 'BG'], cubeTypes: [] },
  { name: 'Dread Return', powerScore: 0.72, archetypes: ['UB', 'BG'], cubeTypes: [] },
  { name: 'Sheoldred, Whispering One', powerScore: 0.82, archetypes: ['UB', 'BG'], cubeTypes: [] },
  { name: 'Stitcher\'s Supplier', powerScore: 0.58, archetypes: ['UB', 'BG'], cubeTypes: [] },
  { name: 'Carrion Feeder', powerScore: 0.55, archetypes: ['BR', 'BG'], cubeTypes: [] },

  // ===== Red =====
  { name: 'Lightning Bolt', powerScore: 0.90, archetypes: ['UR', 'BR', 'RG', 'RW'], cubeTypes: [] },
  { name: 'Chain Lightning', powerScore: 0.78, archetypes: ['UR', 'BR', 'RG', 'RW'], cubeTypes: [] },
  { name: 'Goblin Guide', powerScore: 0.82, archetypes: ['RW', 'BR', 'RG'], cubeTypes: [] },
  { name: 'Monastery Swiftspear', powerScore: 0.78, archetypes: ['UR', 'RW', 'BR'], cubeTypes: [] },
  { name: 'Goblin Rabblemaster', powerScore: 0.80, archetypes: ['RW', 'BR', 'RG'], cubeTypes: [] },
  { name: 'Seasoned Pyromancer', powerScore: 0.72, archetypes: ['UR', 'BR', 'RG'], cubeTypes: [] },
  { name: 'Fable of the Mirror-Breaker', powerScore: 0.85, archetypes: ['UR', 'BR', 'RG'], cubeTypes: [] },
  { name: 'Dragon\'s Rage Channeler', powerScore: 0.75, archetypes: ['UR', 'BR'], cubeTypes: [] },
  { name: 'Wheel of Fortune', powerScore: 0.90, archetypes: ['UR', 'BR'], cubeTypes: [] },
  { name: 'Sneak Attack', powerScore: 0.85, archetypes: ['UR', 'BR', 'RG'], cubeTypes: [] },
  { name: 'Through the Breach', powerScore: 0.80, archetypes: ['UR', 'RG'], cubeTypes: [] },
  { name: 'Fiery Confluence', powerScore: 0.72, archetypes: ['UR', 'RW'], cubeTypes: [] },
  { name: 'Abrade', powerScore: 0.68, archetypes: ['UR', 'BR', 'RW'], cubeTypes: [] },
  { name: 'Daretti, Scrap Savant', powerScore: 0.70, archetypes: ['UR', 'BR'], cubeTypes: [] },
  { name: 'Embereth Shieldbreaker', powerScore: 0.58, archetypes: ['RW', 'BR'], cubeTypes: [] },
  { name: 'Kiki-Jiki, Mirror Breaker', powerScore: 0.82, archetypes: ['UR', 'BR', 'RG'], cubeTypes: [] },
  { name: 'Hellrider', powerScore: 0.72, archetypes: ['RW', 'BR', 'RG'], cubeTypes: [] },
  { name: 'Ragavan, Nimble Pilferer', powerScore: 0.88, archetypes: ['UR', 'RW', 'BR'], cubeTypes: [] },
  { name: 'Bloodthirsty Adversary', powerScore: 0.65, archetypes: ['UR', 'BR'], cubeTypes: [] },

  // ===== Green =====
  { name: 'Llanowar Elves', powerScore: 0.82, archetypes: ['RG', 'UG', 'BG', 'GW'], cubeTypes: [] },
  { name: 'Elvish Mystic', powerScore: 0.78, archetypes: ['RG', 'UG', 'BG', 'GW'], cubeTypes: [] },
  { name: 'Birds of Paradise', powerScore: 0.88, archetypes: [], cubeTypes: [] },
  { name: 'Noble Hierarch', powerScore: 0.85, archetypes: ['GW', 'UG'], cubeTypes: [] },
  { name: 'Tarmogoyf', powerScore: 0.78, archetypes: ['BG', 'RG'], cubeTypes: [] },
  { name: 'Scavenging Ooze', powerScore: 0.75, archetypes: ['BG', 'UG', 'GW'], cubeTypes: [] },
  { name: 'Sylvan Library', powerScore: 0.85, archetypes: ['BG', 'UG', 'GW'], cubeTypes: [] },
  { name: 'Craterhoof Behemoth', powerScore: 0.88, archetypes: ['RG', 'GW', 'UG'], cubeTypes: [] },
  { name: 'Primeval Titan', powerScore: 0.88, archetypes: ['RG', 'UG', 'BG'], cubeTypes: [] },
  { name: 'Tireless Tracker', powerScore: 0.72, archetypes: ['UG', 'GW', 'BG'], cubeTypes: [] },
  { name: 'Oracle of Mul Daya', powerScore: 0.78, archetypes: ['UG', 'RG', 'BG'], cubeTypes: [] },
  { name: 'Courser of Kruphix', powerScore: 0.68, archetypes: ['UG', 'GW', 'BG'], cubeTypes: [] },
  { name: 'Natural Order', powerScore: 0.85, archetypes: ['UG', 'RG'], cubeTypes: [] },
  { name: 'Green Sun\'s Zenith', powerScore: 0.85, archetypes: ['RG', 'UG', 'GW', 'BG'], cubeTypes: [] },
  { name: 'Questing Beast', powerScore: 0.78, archetypes: ['RG', 'BG'], cubeTypes: [] },
  { name: 'Vorinclex, Monstrous Raider', powerScore: 0.72, archetypes: ['RG', 'GW', 'UG'], cubeTypes: [] },
  { name: 'Esika\'s Chariot', powerScore: 0.72, archetypes: ['GW', 'RG'], cubeTypes: [] },
  { name: 'Endurance', powerScore: 0.80, archetypes: ['BG', 'UG', 'GW'], cubeTypes: [] },
  { name: 'Avenger of Zendikar', powerScore: 0.82, archetypes: ['GW', 'RG', 'UG'], cubeTypes: [] },
  { name: 'Dryad Arbor', powerScore: 0.65, archetypes: ['UG', 'RG', 'GW'], cubeTypes: [] },
  { name: 'Eternal Witness', powerScore: 0.72, archetypes: ['BG', 'UG', 'GW'], cubeTypes: [] },
  { name: 'Acidic Slime', powerScore: 0.55, archetypes: ['BG', 'UG'], cubeTypes: [] },

  // ===== Multicolor =====
  { name: 'Baleful Strix', powerScore: 0.80, archetypes: ['UB'], cubeTypes: [] },
  { name: 'The Scarab God', powerScore: 0.85, archetypes: ['UB'], cubeTypes: [] },
  { name: 'Soulherder', powerScore: 0.65, archetypes: ['WU'], cubeTypes: [] },
  { name: 'Teferi, Time Raveler', powerScore: 0.90, archetypes: ['WU'], cubeTypes: [] },
  { name: 'Fractured Identity', powerScore: 0.78, archetypes: ['WU'], cubeTypes: [] },
  { name: 'Dragonlord Ojutai', powerScore: 0.72, archetypes: ['WU'], cubeTypes: [] },
  { name: 'Kolaghan\'s Command', powerScore: 0.78, archetypes: ['BR', 'RW'], cubeTypes: [] },
  { name: 'Daretti, Ingenious Iconoclast', powerScore: 0.72, archetypes: ['BR'], cubeTypes: [] },
  { name: 'Mayhem Devil', powerScore: 0.65, archetypes: ['BR', 'BG'], cubeTypes: [] },
  { name: 'Murderous Redcap', powerScore: 0.55, archetypes: ['BR', 'BG'], cubeTypes: [] },
  { name: 'Bloodbraid Elf', powerScore: 0.75, archetypes: ['RG', 'BR'], cubeTypes: [] },
  { name: 'Huntmaster of the Fells', powerScore: 0.68, archetypes: ['RG'], cubeTypes: [] },
  { name: 'Dragonlord Atarka', powerScore: 0.72, archetypes: ['RG'], cubeTypes: [] },
  { name: 'Kitchen Finks', powerScore: 0.72, archetypes: ['GW', 'WB'], cubeTypes: [] },
  { name: 'Knight of the Reliquary', powerScore: 0.75, archetypes: ['GW', 'UG'], cubeTypes: [] },
  { name: 'Voice of Resurgence', powerScore: 0.78, archetypes: ['GW'], cubeTypes: [] },
  { name: 'Trostani Discordant', powerScore: 0.62, archetypes: ['GW'], cubeTypes: [] },
  { name: 'Lingering Souls', powerScore: 0.80, archetypes: ['WB'], cubeTypes: [] },
  { name: 'Vindicate', powerScore: 0.78, archetypes: ['WB'], cubeTypes: [] },
  { name: 'Sorin, Solemn Visitor', powerScore: 0.72, archetypes: ['WB'], cubeTypes: [] },
  { name: 'Izzet Charm', powerScore: 0.62, archetypes: ['UR'], cubeTypes: [] },
  { name: 'Electrolyze', powerScore: 0.68, archetypes: ['UR'], cubeTypes: [] },
  { name: 'Dack Fayden', powerScore: 0.78, archetypes: ['UR'], cubeTypes: [] },
  { name: 'Prismari Command', powerScore: 0.62, archetypes: ['UR'], cubeTypes: [] },
  { name: 'Deathrite Shaman', powerScore: 0.85, archetypes: ['BG', 'UB'], cubeTypes: [] },
  { name: 'Abrupt Decay', powerScore: 0.78, archetypes: ['BG'], cubeTypes: [] },
  { name: 'Assassin\'s Trophy', powerScore: 0.82, archetypes: ['BG'], cubeTypes: [] },
  { name: 'Meren of Clan Nel Toth', powerScore: 0.72, archetypes: ['BG'], cubeTypes: [] },
  { name: 'Grist, the Hunger Tide', powerScore: 0.68, archetypes: ['BG'], cubeTypes: [] },
  { name: 'Figure of Destiny', powerScore: 0.72, archetypes: ['RW', 'BR'], cubeTypes: [] },
  { name: 'Boros Charm', powerScore: 0.70, archetypes: ['RW'], cubeTypes: [] },
  { name: 'Aurelia, Exemplar of Justice', powerScore: 0.68, archetypes: ['RW'], cubeTypes: [] },
  { name: 'Tajic, Legion\'s Edge', powerScore: 0.58, archetypes: ['RW'], cubeTypes: [] },
  { name: 'Coiling Oracle', powerScore: 0.72, archetypes: ['UG'], cubeTypes: [] },
  { name: 'Growth Spiral', powerScore: 0.62, archetypes: ['UG'], cubeTypes: [] },
  { name: 'Uro, Titan of Nature\'s Wrath', powerScore: 0.90, archetypes: ['UG', 'BG'], cubeTypes: [] },
  { name: 'Hydroid Krasis', powerScore: 0.78, archetypes: ['UG'], cubeTypes: [] },

  // ===== Colorless =====
  { name: 'Black Lotus', powerScore: 0.99, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Mox Sapphire', powerScore: 0.97, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Mox Jet', powerScore: 0.97, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Mox Ruby', powerScore: 0.97, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Mox Pearl', powerScore: 0.97, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Mox Emerald', powerScore: 0.97, archetypes: [], cubeTypes: ['powered'] },
  { name: 'Sol Ring', powerScore: 0.90, archetypes: [], cubeTypes: [] },
  { name: 'Mana Crypt', powerScore: 0.92, archetypes: [], cubeTypes: [] },
  { name: 'Mana Vault', powerScore: 0.82, archetypes: [], cubeTypes: [] },
  { name: 'Chrome Mox', powerScore: 0.78, archetypes: [], cubeTypes: [] },
  { name: 'Mox Diamond', powerScore: 0.80, archetypes: [], cubeTypes: [] },
  { name: 'Smuggler\'s Copter', powerScore: 0.78, archetypes: ['RW', 'WB', 'GW'], cubeTypes: [] },
  { name: 'Batterskull', powerScore: 0.75, archetypes: ['RW', 'WU'], cubeTypes: [] },
  { name: 'Umezawa\'s Jitte', powerScore: 0.88, archetypes: ['RW', 'WB', 'GW'], cubeTypes: [] },
  { name: 'Sword of Fire and Ice', powerScore: 0.82, archetypes: ['RW', 'WU'], cubeTypes: [] },
  { name: 'Sword of Feast and Famine', powerScore: 0.82, archetypes: ['RW', 'WU', 'BG'], cubeTypes: [] },
  { name: 'Aether Vial', powerScore: 0.78, archetypes: ['RW', 'GW', 'BR'], cubeTypes: [] },
  { name: 'Sensei\'s Divining Top', powerScore: 0.72, archetypes: ['UR', 'WU', 'UB'], cubeTypes: [] },
  { name: 'Engineered Explosives', powerScore: 0.72, archetypes: [], cubeTypes: [] },
  { name: 'Walking Ballista', powerScore: 0.80, archetypes: ['GW', 'BR', 'BG'], cubeTypes: [] },
  { name: 'Wurmcoil Engine', powerScore: 0.82, archetypes: [], cubeTypes: [] },
  { name: 'Hangarback Walker', powerScore: 0.68, archetypes: ['GW', 'BR'], cubeTypes: [] },
  { name: 'Emrakul, the Promised End', powerScore: 0.82, archetypes: ['UG', 'UB', 'RG'], cubeTypes: [] },
  { name: 'Myr Battlesphere', powerScore: 0.65, archetypes: ['WU'], cubeTypes: [] },
];

export interface SignpostEntry {
  name: string;
  archetype: ArchetypeKey;
  isGold: boolean;
  isUncommon: boolean;
}

export const SIGNPOST_UNCOMMONS: SignpostEntry[] = [
  // ===== Khans of Tarkir block (wedge gold uncommons) =====
  { name: 'Mantis Rider', archetype: 'RW', isGold: true, isUncommon: false }, // Jeskai — actually rare, but iconic
  { name: 'Siege Rhino', archetype: 'BG', isGold: true, isUncommon: false },
  { name: 'Savage Knuckleblade', archetype: 'RG', isGold: true, isUncommon: false },

  // ===== Ravnica block gold uncommons (the canonical signpost cards) =====
  { name: 'Soulherder', archetype: 'WU', isGold: true, isUncommon: true },
  { name: 'Cloudblazer', archetype: 'WU', isGold: true, isUncommon: true },
  { name: 'Reflector Mage', archetype: 'WU', isGold: true, isUncommon: true },
  { name: 'Baleful Strix', archetype: 'UB', isGold: true, isUncommon: true },
  { name: 'Dimir Charm', archetype: 'UB', isGold: true, isUncommon: true },
  { name: 'Fallen Shinobi', archetype: 'UB', isGold: true, isUncommon: true },
  { name: 'Terminate', archetype: 'BR', isGold: true, isUncommon: true },
  { name: 'Dreadbore', archetype: 'BR', isGold: true, isUncommon: false },
  { name: 'Mayhem Devil', archetype: 'BR', isGold: true, isUncommon: true },
  { name: 'Bloodbraid Elf', archetype: 'RG', isGold: true, isUncommon: true },
  { name: 'Gruul Spellbreaker', archetype: 'RG', isGold: true, isUncommon: false },
  { name: 'Rhythm of the Wild', archetype: 'RG', isGold: true, isUncommon: true },
  { name: 'Kitchen Finks', archetype: 'GW', isGold: true, isUncommon: true },
  { name: 'Knight of Autumn', archetype: 'GW', isGold: true, isUncommon: false },
  { name: 'Voice of Resurgence', archetype: 'GW', isGold: true, isUncommon: false },
  { name: 'Lingering Souls', archetype: 'WB', isGold: true, isUncommon: true },
  { name: 'Tidehollow Sculler', archetype: 'WB', isGold: true, isUncommon: true },
  { name: 'Sin Collector', archetype: 'WB', isGold: true, isUncommon: true },
  { name: 'Izzet Charm', archetype: 'UR', isGold: true, isUncommon: true },
  { name: 'Electrolyze', archetype: 'UR', isGold: true, isUncommon: true },
  { name: 'Prismari Command', archetype: 'UR', isGold: true, isUncommon: false },
  { name: 'Deathrite Shaman', archetype: 'BG', isGold: true, isUncommon: false },
  { name: 'Assassin\'s Trophy', archetype: 'BG', isGold: true, isUncommon: false },
  { name: 'Grisly Salvage', archetype: 'BG', isGold: true, isUncommon: true },
  { name: 'Boros Charm', archetype: 'RW', isGold: true, isUncommon: true },
  { name: 'Boros Reckoner', archetype: 'RW', isGold: true, isUncommon: false },
  { name: 'Heroic Reinforcements', archetype: 'RW', isGold: true, isUncommon: true },
  { name: 'Coiling Oracle', archetype: 'UG', isGold: true, isUncommon: true },
  { name: 'Growth Spiral', archetype: 'UG', isGold: true, isUncommon: true },
  { name: 'Ice-Fang Coatl', archetype: 'UG', isGold: true, isUncommon: false },

  // ===== Modern Horizons 1 & 2 signposts =====
  { name: 'Soulherder', archetype: 'WU', isGold: true, isUncommon: true },
  { name: 'Ice-Fang Coatl', archetype: 'UG', isGold: true, isUncommon: false },
  { name: 'Wrenn and Six', archetype: 'RG', isGold: true, isUncommon: false },
  { name: 'Giver of Runes', archetype: 'WU', isGold: false, isUncommon: false }, // monowhite, fits WU
  { name: 'Unsettled Mariner', archetype: 'WU', isGold: true, isUncommon: false },
  { name: 'Seasoned Pyromancer', archetype: 'UR', isGold: false, isUncommon: false },
  { name: 'Archmage\'s Charm', archetype: 'WU', isGold: false, isUncommon: false },

  // ===== Monocolor archetype anchors =====
  { name: 'Thalia\'s Lieutenant', archetype: 'GW', isGold: false, isUncommon: false },
  { name: 'Champion of the Parish', archetype: 'RW', isGold: false, isUncommon: false },
  { name: 'Goblin Rabblemaster', archetype: 'RW', isGold: false, isUncommon: false },
  { name: 'Young Pyromancer', archetype: 'UR', isGold: false, isUncommon: true },
  { name: 'Guttersnipe', archetype: 'UR', isGold: false, isUncommon: true },
  { name: 'Blood Artist', archetype: 'BR', isGold: false, isUncommon: true },
  { name: 'Zulaport Cutthroat', archetype: 'BR', isGold: false, isUncommon: true },
  { name: 'Satyr Wayfinder', archetype: 'BG', isGold: false, isUncommon: true },
  { name: 'Stitcher\'s Supplier', archetype: 'BG', isGold: false, isUncommon: true },
  { name: 'Ajani\'s Pridemate', archetype: 'WB', isGold: false, isUncommon: true },
];

export interface FixingLandTier {
  tier: number;
  cubeTypes: string[];
  lands: string[];
}

export const FIXING_LAND_TIERS: FixingLandTier[] = [
  {
    tier: 1,
    cubeTypes: ['powered', 'unpowered', 'legacy'],
    lands: [
      'Scalding Tarn', 'Polluted Delta', 'Flooded Strand', 'Windswept Heath',
      'Wooded Foothills', 'Bloodstained Mire', 'Misty Rainforest', 'Verdant Catacombs',
      'Marsh Flats', 'Arid Mesa',
      'Tundra', 'Underground Sea', 'Badlands', 'Taiga', 'Savannah',
      'Scrubland', 'Volcanic Island', 'Bayou', 'Plateau', 'Tropical Island',
      'Prismatic Vista', 'Fabled Passage',
    ],
  },
  {
    tier: 2,
    cubeTypes: ['powered', 'unpowered', 'legacy', 'modern'],
    lands: [
      'Hallowed Fountain', 'Watery Grave', 'Blood Crypt', 'Stomping Ground', 'Temple Garden',
      'Godless Shrine', 'Steam Vents', 'Overgrown Tomb', 'Sacred Foundry', 'Breeding Pool',
      'Mana Confluence', 'City of Brass', 'Gemstone Mine', 'Reflecting Pool',
      'Cavern of Souls', 'Mutavault', 'Urborg, Tomb of Yawgmoth',
    ],
  },
  {
    tier: 3,
    cubeTypes: ['powered', 'unpowered', 'legacy', 'modern', 'peasant'],
    lands: [
      'Glacial Fortress', 'Drowned Catacomb', 'Dragonskull Summit', 'Rootbound Crag', 'Sunpetal Grove',
      'Isolated Chapel', 'Sulfur Falls', 'Woodland Cemetery', 'Clifftop Retreat', 'Hinterland Harbor',
      'Concealed Courtyard', 'Spirebluff Canal', 'Blooming Marsh', 'Inspiring Vantage', 'Botanical Sanctum',
      'Shivan Reef', 'Caves of Koilos', 'Llanowar Wastes', 'Sulfurous Springs', 'Karplusan Forest',
      'Adarkar Wastes', 'Underground River', 'Battlefield Forge', 'Brushland', 'Yavimaya Coast',
      'Mystic Gate', 'Sunken Ruins', 'Graven Cairns', 'Fire-Lit Thicket', 'Wooded Bastion',
      'Fetid Heath', 'Cascade Bluffs', 'Twilight Mire', 'Rugged Prairie', 'Flooded Grove',
    ],
  },
  {
    tier: 4,
    cubeTypes: ['powered', 'unpowered', 'legacy', 'modern', 'peasant', 'pauper'],
    lands: [
      'Temple of Enlightenment', 'Temple of Deceit', 'Temple of Malice', 'Temple of Abandon', 'Temple of Plenty',
      'Temple of Silence', 'Temple of Epiphany', 'Temple of Malady', 'Temple of Triumph', 'Temple of Mystery',
      'Meandering River', 'Submerged Boneyard', 'Cinder Barrens', 'Timber Gorge', 'Tranquil Expanse',
      'Forsaken Sanctuary', 'Highland Lake', 'Foul Orchard', 'Stone Quarry', 'Woodland Stream',
      'Command Tower', 'Exotic Orchard', 'Path of Ancestry',
      'Arcane Signet', 'Fellwar Stone', 'Coldsteel Heart',
    ],
  },
];
